-- AlterTable
ALTER TABLE "PayrollConfig"
ADD COLUMN "advanceRecovery" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "accommodationDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "loanEmi" DOUBLE PRECISION NOT NULL DEFAULT 0;
